#!/usr/bin/python
import boto3
import botocore

s3 = boto3.resource('s3')
bucket = s3.Bucket('a2017-03-02')
exists = True
try:
    s3.meta.client.head_bucket(Bucket='mybucket')
except botocore.exceptions.ClientError as e:
    # If a client error is thrown, then check that it was a 404 error.
    # If it was a 404 error, then the bucket does not exist.
    error_code = int(e.response['Error']['Code'])
    if error_code == 404:
        exists = False

for key in bucket.objects.all():
    key.delete()
bucket.delete()
